# Render Blueprint: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: labor-code-ra
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/info
